const counryList: { country: string; code: string }[] = [
    { country: "Австралия", code: "+61" },
    { country: "Австрия", code: "+43" },
    { country: "Азербайджан", code: "+994" },
    { country: "Албания", code: "+355" },
    { country: "Алжир", code: "+213" },
    { country: "Аляска", code: "+1 907" },
    { country: "Американское Самоа", code: "+1 684" },
    { country: "Ангилья", code: "+1 264" },
    { country: "Ангола", code: "+244" },
    { country: "Андорра", code: "+376" },
    { country: "Антигуа и Барбуда", code: "+1 268" },
    { country: "Аргентина", code: "+54" },
    { country: "Армения", code: "+374" },
    { country: "Аруба", code: "+297" },
    { country: "Афганистан", code: "+93" },
    { country: "Багамские Острова", code: "+1 242" },
    { country: "Бангладеш", code: "+880" },
    { country: "Барбадос", code: "+1 246" },
    { country: "Бахрейн", code: "+973" },
    { country: "Белиз", code: "+501" },
    { country: "Белоруссия", code: "+375" },
    { country: "Бельгия", code: "+32" },
    { country: "Бенин", code: "+229" },
    { country: "Бермудские Острова", code: "+1 441" },
    { country: "Болгария", code: "+359" },
    { country: "Боливия", code: "+591" },
    { country: "Бонэйр", code: "+599" },
    { country: "Босния и Герцеговина", code: "+387" },
    { country: "Ботсвана", code: "+267" },
    { country: "Бразилия", code: "+55" },
    { country: "Бруней", code: "+673" },
    { country: "Буркина-Фасо", code: "+226" },
    { country: "Бурунди", code: "+257" },
    { country: "Бутан", code: "+975" },
    { country: "Вануату", code: "+678" },
    { country: "Ватикан", code: "+39" },
    { country: "Ватикан", code: "+379" },
    { country: "Великобритания", code: "+44" },
    { country: "Венгрия", code: "+36" },
    { country: "Венесуэла", code: "+58" },
    { country: "Виргинские Острова", code: "+1 284" },
    { country: "Виргинские Острова (США)", code: "+1 340" },
    { country: "Восточный Тимор", code: "+670" },
    { country: "Вьетнам", code: "+84" },
    { country: "Габон", code: "+241" },
    { country: "Гавайи", code: "+1 808" },
    { country: "Гайана", code: "+592" },
    { country: "Гамбия", code: "+220" },
    { country: "Гана", code: "+233" },
    { country: "Гваделупа", code: "+590" },
    { country: "Гватемала", code: "+502" },
    { country: "Гвиана (департамент Франции)", code: "+594" },
    { country: "Гвинея", code: "+224" },
    { country: "Гвинея-Бисау", code: "+245" },
    { country: "Германия", code: "+49" },
    { country: "Гернси", code: "+44 1481" },
    { country: "Гибралтар", code: "+350" },
    { country: "Гондурас", code: "+504" },
    { country: "Гонконг", code: "+852" },
    { country: "Государство Палестина", code: "+970" },
    { country: "Гренада", code: "+1 473" },
    { country: "Гренландия", code: "+299" },
    { country: "Греция", code: "+30" },
    { country: "Грузия", code: "+995" },
    { country: "Гуам", code: "+1 671" },
    { country: "Дания", code: "+45" },
    { country: "Демократическая Республика Конго", code: "+243" },
    { country: "Джерси (остров)", code: "+44 1534" },
    { country: "Джибути", code: "+253" },
    { country: "Диего-Гарсия", code: "+246" },
    { country: "Доминика", code: "+1 767" },
    { country: "Доминиканская Республика", code: "+1 809" },
    { country: "Доминиканская Республика", code: "+1 829" },
    { country: "Доминиканская Республика", code: "+1 849" },
    { country: "Египет", code: "+20" },
    { country: "Замбия", code: "+260" },
    { country: "Западная Сахара", code: "+212" },
    { country: "Зимбабве", code: "+263" },
    { country: "Йемен", code: "+967" },
    { country: "Израиль", code: "+972" },
    { country: "Индия", code: "+91" },
    { country: "Индонезия", code: "+62" },
    { country: "Иордания", code: "+962" },
    { country: "Ирак", code: "+964" },
    { country: "Иран", code: "+98" },
    { country: "Ирландия", code: "+353" },
    { country: "Исландия", code: "+354" },
    { country: "Испания", code: "+34" },
    { country: "Италия", code: "+39" },
    { country: "Кабо-Верде", code: "+238" },
    { country: "Казахстан", code: "+7" },
    { country: "Камбоджа", code: "+855" },
    { country: "Камерун", code: "+237" },
    { country: "Канада", code: "+1" },
    { country: "Канарские острова", code: "+34" },
    { country: "Катар", code: "+974" },
    { country: "Кения", code: "+254" },
    { country: "Киргизия", code: "+996" },
    { country: "Кирибати", code: "+686" },
    { country: "Китайская Народная Республика", code: "+86" },
    { country: "Кокосовые острова", code: "+61 891" },
    { country: "Колумбия", code: "+57" },
    { country: "Коморы", code: "+269" },
    { country: "Корейская Народно-Демократическая Республика", code: "+850" },
    { country: "Коста-Рика", code: "+506" },
    { country: "Кот-д’Ивуар", code: "+225" },
    { country: "Куба", code: "+53" },
    { country: "Кувейт", code: "+965" },
    { country: "Кюрасао", code: "+599" },
    { country: "Лаос", code: "+856" },
    { country: "Латвия", code: "+371" },
    { country: "Лесото", code: "+266" },
    { country: "Либерия", code: "+231" },
    { country: "Ливан", code: "+961" },
    { country: "Ливия", code: "+218" },
    { country: "Литва", code: "+370" },
    { country: "Лихтенштейн", code: "+423" },
    { country: "Люксембург", code: "+352" },
    { country: "Маврикий", code: "+230" },
    { country: "Мавритания", code: "+222" },
    { country: "Мадагаскар", code: "+261" },
    { country: "Майотта", code: "+262" },
    { country: "Макао", code: "+853" },
    { country: "Малави", code: "+265" },
    { country: "Малайзия", code: "+60" },
    { country: "Мали", code: "+223" },
    { country: "Мальдивы", code: "+960" },
    { country: "Мальта", code: "+356" },
    { country: "Марокко", code: "+212" },
    { country: "Мартиника", code: "+596" },
    { country: "Маршалловы Острова", code: "+692" },
    { country: "Мексика", code: "+52" },
    { country: "Мозамбик", code: "+258" },
    { country: "Молдавия", code: "+373" },
    { country: "Монако", code: "+377" },
    { country: "Монголия", code: "+976" },
    { country: "Монтсеррат", code: "+1 664" },
    { country: "Мьянма", code: "+95" },
    { country: "Намибия", code: "+264" },
    { country: "Науру", code: "+674" },
    { country: "Непал", code: "+977" },
    { country: "Нигер", code: "+227" },
    { country: "Нигерия", code: "+234" },
    { country: "Нидерландские Антильские острова", code: "+599" },
    { country: "Нидерланды", code: "+31" },
    { country: "Никарагуа", code: "+505" },
    { country: "Ниуэ", code: "+683" },
    { country: "Новая Зеландия", code: "+64" },
    { country: "Новая Каледония", code: "+687" },
    { country: "Норвегия", code: "+47" },
    { country: "Объединённые Арабские Эмираты", code: "+971" },
    { country: "Оман", code: "+968" },
    { country: "Остров Вознесения", code: "+247" },
    { country: "Остров Вознесения", code: "+290" },
    { country: "Остров Мэн", code: "+44 1624" },
    { country: "Остров Норфолк", code: "+672" },
    { country: "Остров Рождества", code: "+61" },
    { country: "Остров Святой Елены", code: "+247" },
    { country: "Остров Святой Елены", code: "+290" },
    { country: "Острова Кайман", code: "+1 345" },
    { country: "Острова Кука", code: "+682" },
    { country: "Острова Питкэрн", code: "+64" },
    { country: "Пакистан", code: "+92" },
    { country: "Палау", code: "+680" },
    { country: "Панама", code: "+507" },
    { country: "Папуа - Новая Гвинея", code: "+675" },
    { country: "Парагвай", code: "+595" },
    { country: "Перу", code: "+51" },
    { country: "Польша", code: "+48" },
    { country: "Португалия", code: "+351" },
    { country: "Пуэрто-Рико", code: "+1 787" },
    { country: "Пуэрто-Рико", code: "+1 939" },
    { country: "Республика Гаити", code: "+509" },
    { country: "Республика Кипр", code: "+357" },
    { country: "Республика Конго", code: "+242" },
    { country: "Республика Корея", code: "+82" },
    { country: "Республика Косово", code: "+383" },
    { country: "Республика Македония", code: "+389" },
    { country: "Реюньон", code: "+262" },
    { country: "Россия", code: "+7" },
    { country: "Руанда", code: "+250" },
    { country: "Румыния", code: "+40" },
    { country: "Саба (остров)", code: "+599" },
    { country: "Сальвадор", code: "+503" },
    { country: "Самоа", code: "+685" },
    { country: "Сан-Марино", code: "+378" },
    { country: "Сан-Томе и Принсипи", code: "+239" },
    { country: "Саудовская Аравия", code: "+966" },
    { country: "Свазиленд", code: "+268" },
    { country: "Северные Марианские Острова", code: "+1 670" },
    { country: "Сейшельские Острова", code: "+248" },
    { country: "Сен-Бартелеми", code: "+590" },
    { country: "Сенегал", code: "+221" },
    { country: "Сен-Мартен", code: "+590" },
    { country: "Сен-Пьер и Микелон", code: "+508" },
    { country: "Сент-Винсент и Гренадины", code: "+1 784" },
    { country: "Сент-Китс и Невис (Сент-Кри́стофер и Не́вис)", code: "+1 869" },
    { country: "Сент-Люсия", code: "+1 758" },
    { country: "Сербия", code: "+381" },
    { country: "Сингапур", code: "+65" },
    { country: "Синт-Мартен", code: "+1 721" },
    { country: "Синт-Эстатиус", code: "+599" },
    { country: "Сирия", code: "+963" },
    { country: "Словакия", code: "+421" },
    { country: "Словения", code: "+386" },
    { country: "Соединённые Штаты Америки (США)", code: "+1" },
    { country: "Соломоновы Острова", code: "+677" },
    { country: "Сомали", code: "+252" },
    { country: "Судан", code: "+249" },
    { country: "Суринам", code: "+597" },
    { country: "Сьерра-Леоне", code: "+232" },
    { country: "Таджикистан", code: "+992" },
    { country: "Тайвань", code: "+886" },
    { country: "Таиланд", code: "+66" },
    { country: "Танзания", code: "+255" },
    { country: "Теркс и Кайкос", code: "+1 649" },
    { country: "Того", code: "+228" },
    { country: "Токелау", code: "+690" },
    { country: "Тонга", code: "+676" },
    { country: "Тринидад и Тобаго", code: "+1 868" },
    { country: "Тристан-да-Кунья (острова)", code: "+247" },
    { country: "Тристан-да-Кунья (острова)", code: "+290" },
    { country: "Тристан-да-Кунья (острова)", code: "+44 20" },
    { country: "Тувалу", code: "+688" },
    { country: "Тунис", code: "+216" },
    { country: "Туркмения", code: "+993" },
    { country: "Турция", code: "+90" },
    { country: "Уганда", code: "+256" },
    { country: "Узбекистан", code: "+998" },
    { country: "Украина", code: "+380" },
    { country: "Уоллис и Футуна", code: "+681" },
    { country: "Уругвай", code: "+598" },
    { country: "Фарерские острова", code: "+298" },
    { country: "Федеративные Штаты Микронезии", code: "+691" },
    { country: "Фиджи", code: "+679" },
    { country: "Филиппины", code: "+63" },
    { country: "Финляндия", code: "+358" },
    { country: "Фолклендские острова", code: "+500" },
    { country: "Франция", code: "+33" },
    { country: "Французская Полинезия", code: "+689" },
    { country: "Хорватия", code: "+385" },
    { country: "Центральноафриканская Республика", code: "+236" },
    { country: "Чад", code: "+235" },
    { country: "Черногория", code: "+382" },
    { country: "Чехия", code: "+420" },
    { country: "Чили", code: "+56" },
    { country: "Швейцария", code: "+41" },
    { country: "Швеция", code: "+46" },
    { country: "Шпицберген", code: "+47" },
    { country: "Шри-Ланка", code: "+94" },
    { country: "Эквадор", code: "+593" },
    { country: "Экваториальная Гвинея", code: "+240" },
    { country: "Эритрея", code: "+291" },
    { country: "Эстония", code: "+372" },
    { country: "Эфиопия", code: "+251" },
    { country: "Южно-Африканская Республика", code: "+27" },
    { country: "Южный Судан", code: "+98" },
    { country: "Ямайка", code: "+1 876" },
    { country: "Япония", code: "+81" },
];

export default counryList;
